name: 24/7 Bot

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '*/0.005 * * * *'  # Har 5 daqiqada qayta ishga tushadi

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 1000000000000000000  # MAKSIMAL 360, 350 xavfsiz
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install aiogram==3.15.0 psutil==5.9.6 pyTelegramBotAPI==4.14.0
    
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        OWNER_ID: ${{ secrets.OWNER_ID }}
      run: python Deploy.py
